(SIMP-9519) GLCI: Upgrade build test to pup6+pdk
simp/pupmod-simp-crypto_policy pull request #17
Opened 2021-03-02 22:55 UTC by op-ct

This patch upgrades the GLCI RELENG check's  puppet module build tests
to use Puppet 6 + `pdk build`, replacing (the now EOL) Puppet 5 and
(the deprecated and removed) `puppet module build`.  It also bumps the
Gemfile's minimum PDK version to 2.0+.

(This patch enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.)

CI: SKIP MATRIX
[SIMP-9530] #close
[SIMP-9519] #comment Use GLCI pup6+pdk in pupmod-simp-crypto_policy

2021-03-04 00:49 UTC, op-ct commented
The GitLab CI failure is due to the presence of a `.pdkignore` file that (when present) `pdk build` will use instead of our modules' standard `.pmtignore` file.  

For this reason, we should update the modules to replace `.pmtignore` with `.pdkignore`—our Puppet Forge release actions also use `pdk build` and will also behave like this.  Module release practices have evolved a bit since we made our modules' `.pmtignore`, so there's a discussion the releng Slack about what should be in the new `.pdkignore`.

2021-03-05 02:42 UTC, op-ct commented
Submitted follow-on issue [SIMP-9606] to update Puppetsync.

2021-03-05 13:20 UTC, lnemsick-simp requested changes
This has commented out tests.  (Artifact of debugging module build problem?)

2021-03-08 13:25 UTC, lnemsick-simp approved these changes

2021-03-08 13:27 UTC, merged